resolver 127.0.0.11 valid=10s ipv6=off;

upstream solicitudes_backend {
    zone solicitudes_backend 64k;
    server ms-solicitudes:8081 resolve;
}

upstream indicadores_backend {
    zone indicadores_backend 64k;
    server ms-indicadores:8082 resolve;
}

server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;

    location = /health {
        access_log off;
        add_header Content-Type text/plain;
        return 200 "ok";
    }

    location /api/v1/indicadores/ {
        proxy_pass http://indicadores_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/ {
        proxy_pass http://solicitudes_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /analytics-remote/ {
        try_files $uri $uri/ /analytics-remote/index.html;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
